---
- name: Directory Setup
  hosts: nodes
  tasks: 
    - name: Setup directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ '/mnt/g1/config/sonarr' }}"
        - "{{ '/mnt/g1/config/radarr' }}"
        - "{{ '/mnt/g1/config/plex' }}" 
        - "{{ '/mnt/g1/config/sabnzb' }}"
        - "{{ '/mnt/g2/transcode' }}"
        - "{{ '/mnt/g1/media/tv' }}"
        - "{{ '/mnt/g1/media/movies' }}"
        - "{{ '/mnt/g1/downloads/complete' }}"
        - "{{ '/mnt/g1/downloads/incomplete' }}"
