---
# Credit to github.com/jahrik for this file
- hosts: nodes
  become: true
  vars:
    gluster_mount_dir: /mnt/g1
    gluster_brick_dir: /bricks/brick1
    gluster_brick_name: g1

  tasks:
    - name: Create Primary partition
      parted:
        device: /dev/sda
        number: 1
        state: present

    - name: Create a ext4 filesystem on /dev/sda1
      filesystem:
        fstype: ext4
        dev: /dev/sda1

    - name: Ensure Gluster brick and mount directories exist.
      file:
        path: "{{ item }}"
        state: directory
        mode: 0775
      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: Mount "{{ gluster_brick_dir }}"
      mount:
        path: "{{ gluster_brick_dir }}"
        src: /dev/sda1
        fstype: ext4
        state: mounted

    - name: configure gluster volume
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        cluster: "{{ groups.nodes | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true
      

    - name: Ensure Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev,log-level=WARNING,log-file=/var/log/gluster.log"
        state: mounted
