---
- name: Initial setup
  hosts: nodes

  tasks:
    - name: setting hostname
      hostname:
        name: '{{ nodename }}'
      register: task_result
      
    - name: Upgrade all packages to the latest version
      package:
        name: "*"
        state: latest
      async: 900
      poll: 20

    - name: Reboot immediately
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300   
      
    - name: Install gluster software
      package:
        name: [aptitude, docker.io, parted, glusterfs-server, glusterfs-client, attr]
        state: present

    - name: Reboot immediately
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
