---
- name: Initial setup
  hosts: setupserver

  tasks:
    - name: setting hostname
      hostname:
        name: '{{ nodename }}'
      register: task_result

    - name: Reboot immediately
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: task_result is changed

    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300   
      when: task_result is changed
  
    - name: Install aptitude
      apt:
        name: aptitude
      become: yes

    - name: Install parted
      package:
        name: parted
        state: present

    - name: Install docker.io
      package:
        name: docker.io      
        state: present
      register: task_result
      
    - name: Install gluster software
      apt:
        name: [glusterfs-server, glusterfs-client, attr]
      tags:
        - setup

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
      become: yes

    - name: Reboot immediately
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: task_result is changed

